EXTRAKEY_ENABLE = yes
ENCODER_ENABLE = yes
SPLIT_KEYBOARD = yes
SPLIT_TRANSPORT = mirror

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
# RGB_MATRIX_DRIVER = WS2812
# RGB_MATRIX_KEYPRESSES = yes
OLED_ENABLE = yes
WPM_ENABLE = no

CONSOLE_ENABLE = no         # Console for debug

# optimize
LTO_ENABLE = yes
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
